<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/7/8
 * Time: 20:12
 */
require_once "../../library/Zend/Auth/Adapter/DbTable.php";
class  Base extends Zend_Controller_Action{

    public function init()
    {
        //parent::init(); // TODO: Change the autogenerated stub
        $url = constant("APPLICATION_PATH",'../configs/config.ini');
        $dbconfig = new Zend_Config_Ini($url,"myslq");
        $db = Zend_Db::factory($dbconfig->db);
        $db->query("set names utf8");
        Zend_Db_Table::setDefaultAdapter($db);
        $authAdapter = new Zend_Auth_Adapter_DbTable($db);
        Zend_Registry::set('authAdapter',$authAdapter);
    }
}