<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/7/8
 * Time: 20:21
 */
require_once "Base.php";
class PublicController extends Base{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}